# Generated by Django 5.0 on 2024-01-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='unit_price',
        ),
    ]
