# Generated by Django 5.0 on 2024-01-02 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_data_order_date_remove_orderitem_unit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
